name: VPS-SSH

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          sudo apt update -y
          sudo apt install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh

          echo "root:root" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

          # Generate SSH key
          ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -q -N ""
          echo "Public key:"
          cat ~/.ssh/id_rsa.pub
          echo "Private key:"
          cat ~/.ssh/id_rsa
          
          echo "Your runner IP is:"
          hostname -I
