name: SSH Session

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Tmate Session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
